### ISSUE TITLE
Error: Can't run `npm run dev`

### ISSUE THREAD

**Issue by ndv99** [sportstimes/f1#1068]
Upon cloning the repository and running `npm install` followed by `npm run dev`, I receive the following output:

```bash
> f1@1.0.0 dev
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
Error: ENOENT: no such file or directory, scandir '_public/undefined'
    at Object.readdirSync (node:fs:1405:3)
    at Object.<anonymous> (/home/myusername/Repositories/f1calendar/build/public-assets.js:6:20)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at module.exports (/home/myusername/Repositories/f1calendar/next.config.js:16:3)
    at Object.normalizeConfig (/home/myusername/Repositories/f1calendar/node_modules/next/dist/server/config-shared.js:123:18) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '_public/undefined'
}
```

Not sure if I'm missing a set-up step or something, but if so then it would be nice to have that detailed in the [README](https://github.com/sportstimes/f1/blob/main/README.md?plain=1#L12-L17)

**Comment by ay8s** [comment]
Adjusted the read me which should hopefully cover the issue you're seeing there. Basically need the environment variables to be set. 👍
