### ISSUE TITLE
ERR_INVALID_ARG_TYPE. The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView

### ISSUE THREAD

**Issue by HarDX** [sportstimes/f1#95]
**node -v**
v14.4.0

ready - started server on http://localhost:3000
```
Defining routes from exportPathMap
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received null
    at Object.writeFileSync (fs.js:1380:5)
    at /home/hard/Develop/f1/utils/generate-calendars.js:192:8
    at Object.createEvents (/home/hard/Develop/f1/node_modules/ics/dist/index.js:159:10)
    at Object.<anonymous> (/home/hard/Develop/f1/utils/generate-calendars.js:186:7)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.webpack (/home/hard/Develop/f1/next.config.js:8:7)
    at Object.webpack (/home/hard/Develop/f1/node_modules/next-fonts/index.js:37:27)
    at Object.webpack (/home/hard/Develop/f1/node_modules/next-offline/index.js:108:25)
    at getBaseWebpackConfig (/home/hard/Develop/f1/node_modules/next/dist/build/webpack-config.js:115:330)
    at async Promise.all (index 1)
    at async HotReloader.start (/home/hard/Develop/f1/node_modules/next/dist/server/hot-reloader.js:15:1941)
    at async DevServer.prepare (/home/hard/Develop/f1/node_modules/next/dist/server/next-dev-server.js:10:2363)
    at async /home/hard/Develop/f1/node_modules/next/dist/cli/next-dev.js:21:359 {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by HarDX** [comment]
Remove in utils\generate-calendars.js and it started locally now.
`  ics.createEvents(events, (error, value) => {
  	if (error) {
  		// TODO: Handle an error...
  	}
  	
  	const path = 'public/download/f1-calendar_'+request+'.ics'
    fs.writeFileSync(path, value);    
  });`

**Comment by ay8s** [comment]
Odd, can you try a npm install then run it? Saw this mentioned in another issue. 

Might just need improved documentation.

**Comment by HarDX** [comment]
try npm install, not helped, same error
```
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received null
    at Object.writeFileSync (fs.js:1380:5)
    at /home/hard/Develop/f1_hardx/utils/generate-calendars.js:192:8
    at Object.createEvents (/home/hard/Develop/f1_hardx/node_modules/ics/dist/index.js:159:10)
    at Object.<anonymous> (/home/hard/Develop/f1_hardx/utils/generate-calendars.js:186:7)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.webpack (/home/hard/Develop/f1_hardx/next.config.js:8:7)
    at Object.webpack (/home/hard/Develop/f1_hardx/node_modules/next-fonts/index.js:37:27)
    at Object.webpack (/home/hard/Develop/f1_hardx/node_modules/next-offline/index.js:108:25)
    at getBaseWebpackConfig (/home/hard/Develop/f1_hardx/node_modules/next/dist/build/webpack-config.js:115:330)
    at async Promise.all (index 1)
    at async HotReloader.start (/home/hard/Develop/f1_hardx/node_modules/next/dist/server/hot-reloader.js:15:1941)
    at async DevServer.prepare (/home/hard/Develop/f1_hardx/node_modules/next/dist/server/next-dev-server.js:10:2363)
    at async /home/hard/Develop/f1_hardx/node_modules/next/dist/cli/next-dev.js:21:359 {
  code: 'ERR_INVALID_ARG_TYPE'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! f1@1.0.0 dev: `next-translate && next dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the f1@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hard/.npm/_logs/2020-06-15T20_30_39_308Z-debug.log
```

**cat /home/hard/.npm/_logs/2020-06-15T20_30_39_308Z-debug.log**
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'dev' ]
2 info using npm@6.14.5
3 info using node@v14.4.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle f1@1.0.0~predev: f1@1.0.0
6 info lifecycle f1@1.0.0~dev: f1@1.0.0
7 verbose lifecycle f1@1.0.0~dev: unsafe-perm in lifecycle true
8 verbose lifecycle f1@1.0.0~dev: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/hard/Develop/f1_hardx/node_modules/.bin:/home/hard/bin:/home/hard/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle f1@1.0.0~dev: CWD: /home/hard/Develop/f1_hardx
10 silly lifecycle f1@1.0.0~dev: Args: [ '-c', 'next-translate && next dev' ]
11 silly lifecycle f1@1.0.0~dev: Returned: code: 1  signal: null
12 info lifecycle f1@1.0.0~dev: Failed to exec dev script
13 verbose stack Error: f1@1.0.0 dev: `next-translate && next dev`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1051:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14 verbose pkgid f1@1.0.0
15 verbose cwd /home/hard/Develop/f1_hardx
16 verbose Linux 4.19.84-microsoft-standard
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "dev"
18 verbose node v14.4.0
19 verbose npm  v6.14.5
20 error code ELIFECYCLE
21 error errno 1
22 error f1@1.0.0 dev: `next-translate && next dev`
22 error Exit status 1
23 error Failed at the f1@1.0.0 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by ay8s** [comment]
Thanks, think I have it solved and will merge something soon.

**Comment by ay8s** [comment]
Should be fixed now if you are able to try master 👍

**Comment by HarDX** [comment]
> Should be fixed now if you are able to try master 👍

not helped last changes, and lang selector now absent, and need add to:
**locales/ru/common.json**
`"languageSelector": "Выберите язык",
`
```
Building pages | from pages_ to pages
🔨 /generate [ 'common', 'calendar', 'generate' ]
🔨 / [ 'common', 'calendar', 'calendar' ]
🔨 /timezone/[timezone] [ 'common', 'calendar' ]
🔨 /timezones [ 'common', 'calendar', 'timezones' ]
🔨 /year/[year] [ 'common', 'calendar' ]
🔨 /years [ 'common', 'calendar', 'years', 'calendar' ]
ready - started server on http://localhost:3000
Defining routes from exportPathMap
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received null
    at Object.writeFileSync (fs.js:1380:5)
    at /home/hard/Develop/f1/utils/generate-calendars.js:191:6
    at Object.createEvents (/home/hard/Develop/f1/node_modules/ics/dist/index.js:159:10)
    at Object.<anonymous> (/home/hard/Develop/f1/utils/generate-calendars.js:186:7)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.webpack (/home/hard/Develop/f1/next.config.js:8:7)
    at Object.webpack (/home/hard/Develop/f1/node_modules/next-fonts/index.js:37:27)
    at Object.webpack (/home/hard/Develop/f1/node_modules/next-offline/index.js:108:25)
    at getBaseWebpackConfig (/home/hard/Develop/f1/node_modules/next/dist/build/webpack-config.js:114:302)
    at async Promise.all (index 1)
    at async HotReloader.start (/home/hard/Develop/f1/node_modules/next/dist/server/hot-reloader.js:15:1938)
    at async DevServer.prepare (/home/hard/Develop/f1/node_modules/next/dist/server/next-dev-server.js:10:1565)
    at async /home/hard/Develop/f1/node_modules/next/dist/cli/next-dev.js:21:359 {
  code: 'ERR_INVALID_ARG_TYPE'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! f1@1.0.0 dev: `next-translate && next dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the f1@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hard/.npm/_logs/2020-06-16T08_10_49_202Z-debug.log
```

 **hard  ~  Develop  f1   master ✚ 1  cat /home/hard/.npm/_logs/2020-06-16T08_10_49_202Z-debug.log**
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'dev' ]
2 info using npm@6.14.5
3 info using node@v14.4.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle f1@1.0.0~predev: f1@1.0.0
6 info lifecycle f1@1.0.0~dev: f1@1.0.0
7 verbose lifecycle f1@1.0.0~dev: unsafe-perm in lifecycle true
8 verbose lifecycle f1@1.0.0~dev: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/hard/Develop/f1/node_modules/.bin:/home/hard/bin:/home/hard/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle f1@1.0.0~dev: CWD: /home/hard/Develop/f1
10 silly lifecycle f1@1.0.0~dev: Args: [ '-c', 'next-translate && next dev' ]
11 silly lifecycle f1@1.0.0~dev: Returned: code: 1  signal: null
12 info lifecycle f1@1.0.0~dev: Failed to exec dev script
13 verbose stack Error: f1@1.0.0 dev: `next-translate && next dev`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1051:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14 verbose pkgid f1@1.0.0
15 verbose cwd /home/hard/Develop/f1
16 verbose Linux 4.19.84-microsoft-standard
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "dev"
18 verbose node v14.4.0
19 verbose npm  v6.14.5
20 error code ELIFECYCLE
21 error errno 1
22 error f1@1.0.0 dev: `next-translate && next dev`
22 error Exit status 1
23 error Failed at the f1@1.0.0 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by ay8s** [comment]
Should be resolved as of https://github.com/sportstimes/f1/pull/104

Was able to replicate and run with v14 on my machine after upgrading the npm dependencies.

**Comment by HarDX** [comment]
strange but i update master to commit ba9befb884d1c81ec9c8d3666c49242b0f87243d

But not helped same error
